### ISSUE TITLE
Types of items to have in game?

### ISSUE THREAD

**Issue by jiaweichen99** [ThatAznKid/TeamAsterisk#3]
So armor,swords,wands, and etc. seem like a given but... 
How are we going to execute it? 
One per slot? Infinite amount to hold? etc. etc.

**Comment by cw-cs** [comment]
Likely equipment and weapons with  limited inventory space (6 or 9）

**Comment by jiaweichen99** [comment]
Guess that's it for now... 
Stat buffs mainly, but limited to one of each type I guess. 
Issue closed.
